### PR TITLE
Install and set up Django to project

### PR DESCRIPTION
**Pull request by scholachoi**

### CODE REVIEW

**Comment by EMCain** [comment]
It looks like you need to add some things to .gitignore. Here's a sample for Python projects.

https://github.com/github/gitignore/blob/master/Python.gitignore

You should also ignore the folder that contains the virtualenv, and add any packages that need to be installed in it to a `requirements.txt` file in the project root. Assuming those packages were installed with git, you can generate the file like this: 

```
$ pip freeze > requirements.txt
```

**Comment by scholachoi** [comment]
Thanks @EMCain ! Hope I did it right. I think a lot of the things in that .gitignore template don't apply, but left them in anyway.

**Comment by EMCain** [comment]
@scholachoi sorry I took so long to reply--the gitignore looks good. Can you also add a document in the "docs" folder on how to set up locally?

**Comment by morganpdx** [comment]
@scholachoi looks good! I’ll second the request from @EMcain to remove the venv folder as well as add documentation for setup. Please add it to the readme.md file in the root. Once you finish that I can merge in the PR. Good work!

**Comment by scholachoi** [comment]
I'm confused about the venv folder. @EMCain said to "ignore the folder that contains the virtualenv" which I thought meant that it should be in the .gitignore file, but per @morganpdx I should "**remove** the venv folder." Could you clarify? Thank you!

**Comment by morganpdx** [comment]
Both - the gitignore will ensure it’s not in the repo going forward, but right now your PR includes adding those files. You can remove them from the repo without deleting them; check out this stackoverflow post for details: https://stackoverflow.com/questions/1143796/remove-a-file-from-a-git-repository-without-deleting-it-from-the-local-filesyste

**Comment by scholachoi** [comment]
Thanks @morganpdx ! I understand what I did now. I hope I fixed the problem correctly!

**Review by morganpdx — CHANGES_REQUESTED** [review]
The instructions look fabulous @scholachoi! Just a couple more changes:  add a tip on how to install pip in case the user doesn't have that installed, and be sure to remove all the .pyc files that are included in the commit.  Those are just binary files that get generated from the .py files, and are not necessary in the repo.  You can use the same process you used to remove the /venv folder.  Other than that it's a big 👍 !

**Comment by scholachoi** [comment]
Hmm. I though `git rm --cached *.pyc` would remove all .pyc files but it seems to have only removed 4, from the 'wwcpdx' folder. Git tells me there are no more, but I see 4 more inside the 'website' folder...

**Review by morganpdx — APPROVED** [review]
Looks awesome!  Thanks @scholachoi!

**Pull request merged**
